# Generated by Django 5.2.12 on 2026-03-26 09:42

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_ot_security', '0001_initial'),
        ('users', '0015_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conduit',
            name='security_level',
            field=models.CharField(default='SL-1', max_length=8),
        ),
        migrations.AlterField(
            model_name='conduit',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AlterField(
            model_name='securityzone',
            name='purdue_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='securityzone',
            name='security_level',
            field=models.CharField(default='SL-1', max_length=8),
        ),
        migrations.AlterField(
            model_name='securityzone',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddConstraint(
            model_name='conduit',
            constraint=models.UniqueConstraint(fields=('source_zone', 'target_zone'), name='netbox_ot_security_unique_zone_pair'),
        ),
    ]
