import type { AssetDefinition } from './topologyTypes'

export const assetCatalog: AssetDefinition[] = [
  {
    assetType: 'router',
    label: 'Router Core',
    shortLabel: 'RTR',
    role: 'network',
    defaultZoneId: 'zone-it',
    defaultZoneName: 'Zona IT',
    purdueLevel: 4,
    securityLevel: 'SL-2',
    criticality: 'high',
  },
  {
    assetType: 'switch',
    label: 'Switch Acceso',
    shortLabel: 'SW',
    role: 'network',
    defaultZoneId: 'zone-it',
    defaultZoneName: 'Zona IT',
    purdueLevel: 4,
    securityLevel: 'SL-2',
    criticality: 'high',
  },
  {
    assetType: 'firewall',
    label: 'Firewall Industrial',
    shortLabel: 'FW',
    role: 'security',
    defaultZoneId: 'zone-dmz',
    defaultZoneName: 'Zona DMZ',
    purdueLevel: 3,
    securityLevel: 'SL-3',
    criticality: 'critical',
  },
  {
    assetType: 'server',
    label: 'Servidor SCADA',
    shortLabel: 'SRV',
    role: 'compute',
    defaultZoneId: 'zone-ot-supervision',
    defaultZoneName: 'Zona OT Supervision',
    purdueLevel: 2,
    securityLevel: 'SL-2',
    criticality: 'critical',
  },
  {
    assetType: 'host',
    label: 'Estacion Ingenieria',
    shortLabel: 'ENG',
    role: 'compute',
    defaultZoneId: 'zone-it',
    defaultZoneName: 'Zona IT',
    purdueLevel: 4,
    securityLevel: 'SL-1',
    criticality: 'medium',
  },
  {
    assetType: 'plc',
    label: 'PLC Linea A',
    shortLabel: 'PLC',
    role: 'ot',
    defaultZoneId: 'zone-ot-control',
    defaultZoneName: 'Zona OT Control',
    purdueLevel: 1,
    securityLevel: 'SL-3',
    criticality: 'critical',
  },
  {
    assetType: 'hmi',
    label: 'HMI Celda',
    shortLabel: 'HMI',
    role: 'ot',
    defaultZoneId: 'zone-ot-supervision',
    defaultZoneName: 'Zona OT Supervision',
    purdueLevel: 2,
    securityLevel: 'SL-2',
    criticality: 'high',
  },
  {
    assetType: 'rtu',
    label: 'RTU Remota',
    shortLabel: 'RTU',
    role: 'ot',
    defaultZoneId: 'zone-ot-control',
    defaultZoneName: 'Zona OT Control',
    purdueLevel: 1,
    securityLevel: 'SL-3',
    criticality: 'high',
  },
  {
    assetType: 'wireless_ap',
    label: 'AP Industrial',
    shortLabel: 'AP',
    role: 'network',
    defaultZoneId: 'zone-it',
    defaultZoneName: 'Zona IT',
    purdueLevel: 4,
    securityLevel: 'SL-2',
    criticality: 'medium',
  },
]

export function getAssetDefinition(assetType: string): AssetDefinition {
  return (
    assetCatalog.find((asset) => asset.assetType === assetType) ?? assetCatalog[0]
  )
}
