import type { AssetDefinition } from './topologyTypes'

export const assetCatalog: AssetDefinition[] = [
  {
    assetType: 'router',
    label: 'Router Core',
    shortLabel: 'RTR',
    role: 'network',
    defaultZoneId: 'zone-it',
    defaultZoneName: 'Zona IT',
    purdueLevel: 4,
    securityLevel: 'SL-2',
    criticality: 'high',
    portCount: 4,
    portPrefix: 'eth',
    vlanId: 140,
    vlanName: 'IT Planta',
    defaultProtocols: ['HTTPS', 'SSH', 'SNMP'],
  },
  {
    assetType: 'switch',
    label: 'Switch Acceso',
    shortLabel: 'SW',
    role: 'network',
    defaultZoneId: 'zone-it',
    defaultZoneName: 'Zona IT',
    purdueLevel: 4,
    securityLevel: 'SL-2',
    criticality: 'high',
    portCount: 8,
    portPrefix: 'eth',
    vlanId: 140,
    vlanName: 'IT Planta',
    defaultProtocols: ['SNMP', 'LLDP'],
  },
  {
    assetType: 'firewall',
    label: 'Firewall Industrial',
    shortLabel: 'FW',
    role: 'security',
    defaultZoneId: 'zone-dmz',
    defaultZoneName: 'Zona DMZ',
    purdueLevel: 3,
    securityLevel: 'SL-3',
    criticality: 'critical',
    portCount: 4,
    portPrefix: 'eth',
    vlanId: 130,
    vlanName: 'DMZ Industrial',
    defaultProtocols: ['HTTPS', 'OPC-UA'],
  },
  {
    assetType: 'server',
    label: 'Servidor SCADA',
    shortLabel: 'SRV',
    role: 'compute',
    defaultZoneId: 'zone-ot-supervision',
    defaultZoneName: 'Zona OT Supervision',
    purdueLevel: 2,
    securityLevel: 'SL-2',
    criticality: 'critical',
    portCount: 2,
    portPrefix: 'eth',
    vlanId: 120,
    vlanName: 'OT Supervision',
    defaultProtocols: ['OPC-UA', 'HTTPS'],
  },
  {
    assetType: 'host',
    label: 'Estacion Ingenieria',
    shortLabel: 'ENG',
    role: 'compute',
    defaultZoneId: 'zone-it',
    defaultZoneName: 'Zona IT',
    purdueLevel: 4,
    securityLevel: 'SL-1',
    criticality: 'medium',
    portCount: 1,
    portPrefix: 'eth',
    vlanId: 140,
    vlanName: 'IT Planta',
    defaultProtocols: ['HTTPS', 'RDP'],
  },
  {
    assetType: 'plc',
    label: 'PLC Linea A',
    shortLabel: 'PLC',
    role: 'ot',
    defaultZoneId: 'zone-ot-control',
    defaultZoneName: 'Zona OT Control',
    purdueLevel: 1,
    securityLevel: 'SL-3',
    criticality: 'critical',
    portCount: 2,
    portPrefix: 'eth',
    vlanId: 110,
    vlanName: 'OT Control',
    defaultProtocols: ['Modbus/TCP', 'PROFINET'],
  },
  {
    assetType: 'hmi',
    label: 'HMI Celda',
    shortLabel: 'HMI',
    role: 'ot',
    defaultZoneId: 'zone-ot-supervision',
    defaultZoneName: 'Zona OT Supervision',
    purdueLevel: 2,
    securityLevel: 'SL-2',
    criticality: 'high',
    portCount: 1,
    portPrefix: 'eth',
    vlanId: 120,
    vlanName: 'OT Supervision',
    defaultProtocols: ['OPC-UA', 'HTTPS'],
  },
  {
    assetType: 'rtu',
    label: 'RTU Remota',
    shortLabel: 'RTU',
    role: 'ot',
    defaultZoneId: 'zone-ot-control',
    defaultZoneName: 'Zona OT Control',
    purdueLevel: 1,
    securityLevel: 'SL-3',
    criticality: 'high',
    portCount: 2,
    portPrefix: 'eth',
    vlanId: 110,
    vlanName: 'OT Control',
    defaultProtocols: ['DNP3', 'Modbus/TCP'],
  },
  {
    assetType: 'wireless_ap',
    label: 'AP Industrial',
    shortLabel: 'AP',
    role: 'network',
    defaultZoneId: 'zone-it',
    defaultZoneName: 'Zona IT',
    purdueLevel: 4,
    securityLevel: 'SL-2',
    criticality: 'medium',
    portCount: 1,
    portPrefix: 'wlan',
    vlanId: 140,
    vlanName: 'IT Planta',
    defaultProtocols: ['HTTPS', 'SNMP'],
  },
]

export function getAssetDefinition(assetType: string): AssetDefinition {
  return (
    assetCatalog.find((asset) => asset.assetType === assetType) ?? assetCatalog[0]
  )
}
